spring.application.name=apiGateway

server.port=8084
spring.cloud.gateway.routes[0].id = QuestionService
spring.cloud.gateway.routes[0].uri = lb://QuestionService
spring.cloud.gateway.routes[0].predicates[0]=Path= /question/**      



spring.cloud.gateway.routes[1].id = QuizService
spring.cloud.gateway.routes[1].uri = lb://QuizService
spring.cloud.gateway.routes[1].predicates[0]=Path= /quiz/**        

